services:
  go2rtc:
    image: alexxit/go2rtc:latest
    network_mode: host
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
    restart: unless-stopped

  rtsp-pusher:
    build:
      context: ../..
      dockerfile: examples/rtsp/Dockerfile
    network_mode: host
    environment:
      - DEVICE_INDEX=${DEVICE_INDEX:-}
    volumes:
      - ../../data:/app/examples/rtsp/data
    depends_on:
      - go2rtc
    stdin_open: true
    tty: true
    restart: unless-stopped
