services:
  web:
    build:
      context: ../..
      dockerfile: examples/web/Dockerfile
    network_mode: host
    environment:
      - DEVICE_INDEX=${DEVICE_INDEX:-}
    volumes:
      - ../../data:/app/examples/web/data
    stdin_open: true
    tty: true
    restart: unless-stopped
